---
title: "Final Project US Overview Portion"
author: "Anders Lie"
date: "4/25/2021"
output: html_document
---


```{r, warning=FALSE, message=FALSE}
library(tidyverse)
library(rmarkdown)
library(lubridate)
```

# Preprocessing

```{r}
acc_raw <- read_csv('US_Accidents_Dec20.csv')
census_raw <- read.csv('census2010-2019.csv')
states <- map_data('state')
abv <- read.csv('state_abbrvs.csv', fileEncoding="UTF-8-BOM")


# === Census Preprocessing ===

census <- census_raw %>%
  mutate(across(Census:X2019, function(x){as.numeric(gsub(",", "", x))})) %>%
  separate(Geographic.Area, sep=', ', into=c('City', 'region')) %>%
  group_by(region) %>%
  summarize(
    `2016`=sum(X2016),
    `2017`=sum(X2017),
    `2018`=sum(X2018),
    `2019`=sum(X2019)
  ) %>%
  pivot_longer(`2016`:`2019`, names_to='Year') %>%
  mutate(Year=as.numeric(Year))


# === Accidents Preprocssing ===

acc <- acc_raw %>%
  mutate(Code=State) %>%
  select(-State) %>%
  left_join(abv, by='Code') %>%
  select(Start_Time, Start_Lat, Start_Lng, State) %>%
  mutate(State=tolower(State), Time=ymd_hms(Start_Time)) %>%
  select(-Start_Time)
  
  

```
