---
title: "DS 202 Project"
author: "Eric Steyer"
date: "4/21/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyr)
library(lubridate)
```


```{r}
acc = read.csv("US_Accidents_Dec20.csv")
```
```{r}
acc = separate(acc, Start_Time, into = c("Date", "Time"), sep = " ")
```

```{r}
acc$Date = ymd(acc$Date)
```

```{r}
head(acc)
```
```{r}
acc$Year = year(acc$Date)
acc$Month = month(acc$Date)
acc$Day = day(acc$Date)
```

```{r}
acc16 = acc[acc$Year == 2016,]
acc17 = acc[acc$Year == 2017,]
acc18 = acc[acc$Year == 2018,]
acc19 = acc[acc$Year == 2019,]
acc20 = acc[acc$Year == 2020,]
```

```{r}
daily_acc = acc %>% group_by(Date) %>% summarise(n = n()) %>% mutate(year = year(Date))
```

```{r}
daily_acc %>% ggplot(aes(x=Date, y=n)) + geom_line() + facet_wrap(~year, scales = "free_x") + scale_x_date(date_labels = "%b")
```
```{r}
accthu = acc %>% filter(wday(Date, label = TRUE) == "Thu")
```

```{r}
daily_thu = accthu %>% group_by(Date) %>% summarise(n = n()) %>% mutate(year = year(Date))

daily_thu %>% ggplot(aes(x=Date, y=n)) + geom_line() + facet_wrap(~year, scales = "free_x") + scale_x_date(date_labels = "%b")
```
```{r}
daily_fri %>% filter(year==2018, month(Date)==11) %>% filter(n==min(n))
```
```{r}
daily_acc %>% filter(year != 2016) %>% group_by(month(Date)) %>% summarise(n=sum(n)) %>% rename("month" = "month(Date)") %>% ggplot(aes(x=month, y=n)) + geom_bar(stat = "identity")
```
```{r}
acc %>% filter(Severity==4) %>% group_by(Date) %>% summarise(n = n()) %>% mutate(year = year(Date)) %>% ggplot(aes(x=Date, y=n)) + geom_line() + facet_wrap(~year, scales = "free_x") + scale_x_date(date_labels = "%b")
```
```{r}
daily_acc %>% filter(year == 2020) %>% ggplot(aes(x=Date, y=n)) + geom_line() + facet_wrap(~year, scales = "free_x")
```

```{r}
acc %>% filter(Severity==4, Year==2020) %>% group_by(Date) %>% summarise(n = n()) %>% mutate(year = year(Date)) %>% ggplot(aes(x=Date, y=n)) + geom_line() + facet_wrap(~year, scales = "free_x") + scale_x_date(date_labels = "%b")
```

```{r}
acc %>% filter(Year == 2020, State=="IA") %>% group_by(Date) %>% summarise(n = n()) %>% mutate(year = year(Date)) %>% ggplot(aes(x=Date, y=n)) + geom_line() + facet_wrap(~year, scales = "free_x") + scale_x_date(date_labels = "%b")
```

